version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: backend-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-portfolio_db}
      POSTGRES_USER: ${POSTGRES_USER:-portfolio_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-portfolio_pass}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d:ro

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-dev
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - GO_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB:-portfolio_db}
      - DB_USER=${POSTGRES_USER:-portfolio_user}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-portfolio_pass}
      - DB_SSL_MODE=disable
      - JWT_SECRET=${JWT_SECRET:-your-jwt-secret}
      - KEYCLOAK_URL=${KEYCLOAK_URL:-http://localhost:8080}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM:-master}
    depends_on:
      - postgres
    volumes:
      - .:/app
    working_dir: /app
    command: go run main.go

volumes:
  postgres_data: