version: "3.8"

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-auth
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GIN_MODE=release
      - LOG_LEVEL=info
      - DB_HOST=${DB_HOST:-localhost}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${POSTGRES_DB:-portfolio_db}
      - DB_USER=${POSTGRES_USER:-portfolio_user}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-portfolio_pass}
      - DB_SSLMODE=disable
      - DB_TIMEZONE=UTC
      - JWT_SECRET=${JWT_SECRET:-your-jwt-secret-key}
    networks:
      - portfolio-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  portfolio-network:
    external: true